# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/

app = 'zerolight-backend'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[vm]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
